version: '3.4'

services:
  travelapi:
    image: ${DOCKER_REGISTRY-}travelapi
    build:
      context: .
      dockerfile: Travel/Dockerfile
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://alisahinasya:123456@mysql:3306/Travel

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Travel
      MYSQL_USER: alisahinasya
      MYSQL_PASSWORD: 123456


      